CLIENT_ID = 
CLIENT_SECRET = 
REDIRECT_URI = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
SCOPE = "user-library-read user-read-private user-read-playback-state user-modify-playback-state"
SPEECH_FILE_NAME = "speech.mp3"
TTS_API_KEY = 
TTS_URL = "https://api.eu-gb.text-to-speech.watson.cloud.ibm.com/instances/b105f065-faa3-490b-b033-efc59a9544c5"
